### ISSUE TITLE
Language mismatch between theme and git-revision-date-localized in mkdocs.yml

### ISSUE THREAD

**Issue by nickynicolson** [ObsidianPublisher/follow_template#2]
The `mkdocs.yml` file in `template-gh-pages` specifies `en` as the theme language, but the `git-revision-date-localized` language is set to `fr` - the latter should use the same default.

(apologies if this is not the correct repo for this issue, hard to see where best to report)

**Comment by Mara-Li** [comment]
It is the best repo to report this :)
