### ISSUE TITLE
Expand github readme documentation for the template repository to explain secrets requirement

### ISSUE THREAD

**Issue by nickynicolson** [ObsidianPublisher/follow_template#4]
A github repository generated from the template has a couple of scheduled actions set by default, but the documentation in the github readme does not explain that these require two secrets (GH_PAT and GH_TOKEN). This is included in the detailed documentation at https://obsidian-publisher.netlify.app/template/actions but is easily missed. Without specifying these tokens there are nightly failures.

**Comment by Mara-Li** [comment]
If I understand well, you want me to add some documentation about the github actions ? Is including directly the file (that you linked) is okay, or I need to resume it to just about the two secrets keys ? 

(Personal notes : WHY THEY ARE TWO SAMES GH TOKEN with different name ??? I'm stupid !)

**Comment by Mara-Li** [comment]
Closed in ObsidianPublisher/docs@597428d9593d635739f3effa97a4508426ac89d5
