### ISSUE TITLE
Clarity around auto-opened PR ("version.txt")

### ISSUE THREAD

**Issue by jm3** [ObsidianPublisher/follow_template#5]
![PR version 3 0 3](https://github.com/ObsidianPublisher/template-main/assets/12213/d15bda42-cfcd-42b9-8399-546680692d2a)

Hi, I've been playing with the excellent [ObsidianPublisher/template-gh-pages](https://github.com/ObsidianPublisher/template-gh-pages) workflow. Yesterday my forked repo received an automated pull-request for a new version bump (3.0.3). _(Repo is private so I can't link to the PR; screenshot above)_

Because the automated PR did not contain a changelog link or release notes explaining what this version bump entailed, I spent time poking around in the web of connected repos trying to understand what the effect of merging this PR would be.

My hypotheses about the mysterious `version.txt`, in order, discarded:
- [x] first I thought it corresponded to a **Python** version update, but that seems not to be the case
- [x] then I assumed it was a version for some required **python runtime**
  - for the github workflow? Not sure how to check this.
- [x] then I guessed maybe it was the **mkdocs** version number, but I ruled that out as well
- [ ] now my assumption is that maybe this refers to a change in the **templated workflow actions**? is this right?

Can you please clarify what merging this automated version bump PR will actually change?

**Update**: I found [this corresponding 3.0.3 release](https://github.com/ObsidianPublisher/template-main/releases/tag/3.0.3) in template-main that updates [find_unused_media.py](https://github.com/ObsidianPublisher/template-main/commit/43d765c6b10d3c35e24fdb3e40a28fafbd227b8e). 🎉 

So I _think_ I answered my own question. Maybe it would be ideal to include a link to the release changelog in future automated PR templates if possible, to save users the time of trying to understand what merging a mysterious, un-attributed PR would do :)

Thanks in advance.

Repos I bumped around in, exploring:

* [ObsidianPublisher/docs](https://github.com/ObsidianPublisher/docs)
* [ObsidianPublisher/template-main](https://github.com/ObsidianPublisher/template-main) (actually contains a `version.txt` with a matching 3.0.3 number)
* [ObsidianPublisher/template-gh-pages](https://github.com/ObsidianPublisher/template-gh-pages)

**Comment by Mara-Li** [comment]
Yeah, the `version.txt` file contains the version number, so it is easier to update, and inform also you that there is an update.
I will update the PR message to includes the changelog.
